/* Generated by tools/make_sw.py - do not edit.
   Offline support for a built bundle. The cache name is a hash of the bytes in
   SHELL, so any change to the app produces a new cache and the old one is
   deleted on activate; nothing here needs bumping by hand. */
var VERSION = 'offline-3e87eab99b6c';
var SHELL = [
"index.html",
"site.css",
"site.js",
"theme-sheet.html",
"assets/fonts/inter-greek.woff2",
"assets/fonts/inter-latin-ext.woff2",
"assets/fonts/inter-latin.woff2",
"assets/fonts/jetbrains-mono-greek.woff2",
"assets/fonts/jetbrains-mono-latin-ext.woff2",
"assets/fonts/jetbrains-mono-latin.woff2",
"assets/fonts/newsreader-latin-ext.woff2",
"assets/fonts/newsreader-latin.woff2"
];

self.addEventListener('install', function (event) {
  event.waitUntil((async function () {
    var cache = await caches.open(VERSION);
    /* Individually, not addAll: one 404 in addAll rejects the whole install and
       leaves the device with no worker at all, which is the worst outcome - a
       reader who is told they are offline when they are not. */
    await Promise.all(SHELL.map(function (url) {
      return cache.add(new Request(url, { cache: 'reload' })).catch(function () {});
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', function (event) {
  event.waitUntil((async function () {
    var keys = await caches.keys();
    await Promise.all(keys.map(function (key) {
      return key === VERSION ? null : caches.delete(key);
    }));
    /* claim() so the very first visit is already offline-capable, rather than
       needing a reload before the worker controls anything. */
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', function (event) {
  var request = event.request;
  if (request.method !== 'GET') return;
  var url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    /* Network first, shell second. ignoreSearch because the page may be reached
       through an appearance link (?t=&w=&c=), and that must not miss the cache. */
    event.respondWith((async function () {
      var cached = await caches.match('index.html', { ignoreSearch: true });
      var fresh = null;
      try {
        fresh = await fetch(request);
      } catch (error) {
        fresh = null;              /* no network at all */
      }
      if (fresh && fresh.ok) {
        await cachePut(request, fresh.clone());
        return fresh;
      }
      /* Either the network is gone or the host answered 404 - and this is a
         hash-routed single page, so EVERY navigation belongs to index.html. A
         cached shell is a better answer than a 404 page when the host got the
         path wrong, and the only answer when there is no network. */
      if (cached) return cached;
      if (fresh) return fresh;
      throw new Error('offline with nothing cached');
    })());
    return;
  }

  /* Assets: cache first, fill in the background. Figures and note pages are
     fetched as the reader scrolls, so this is what makes a plane-friendly read
     without pre-downloading 12 MB nobody asked for. */
  event.respondWith((async function () {
    var hit = await caches.match(request, { ignoreSearch: true });
    if (hit) return hit;
    var response = await fetch(request);
    if (response && response.ok && response.type === 'basic') await cachePut(request, response.clone());
    return response;
  })());
});

async function cachePut(request, response) {
  try {
    var cache = await caches.open(VERSION);
    await cache.put(request, response);
  } catch (error) {
    /* A cache that refuses a write (opaque response, quota) must not turn into a
       failed request: the reader gets the bytes either way. */
  }
}
